# Generated by Django 5.0.3 on 2024-03-10 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=20)),
                ('balance', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bank_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bank_account',
                'verbose_name_plural': 'bank_account',
            },
        ),
        migrations.CreateModel(
            name='BankAccountTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_bank_account_transfer', to='apis.bankaccount')),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_bank_account_transfer', to='apis.bankaccount')),
            ],
            options={
                'verbose_name': 'bank_account_transfer',
                'verbose_name_plural': 'bank_account_transfer',
            },
        ),
    ]
